import { Product, Store } from "../types";
export const STORAGE_KEYS = {
  AUTH_TOKEN: "localio_auth_token",
  REFRESH_TOKEN: "localio_refresh_token",
  USER_DATA: "localio_user_data",
  CART: "localio_cart",
  THEME: "localio_theme",
  USER_LOCATION: "localio_user_location",
};
export const API_CONFIG = {
  BASE_URL: " https://local-ecommerce-backend-production.up.railway.app/",
  TIMEOUT: 10000,
};
export const FEES = {
  PLATFORM_FEE: 2.0,
  DEFAULT_DELIVERY_FEE: 15.0,
};
export const MOCK_STORES: Store[] = [
  {
    id: "store_1",
    name: "Greenfield Groceries",
    category: "daily_amenities",
    logoUrl:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=100&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
    rating: 4.6,
    reviewCount: 128,
    distance: 1.2,
    deliveryEta: 20,
    deliveryFee: 15,
    minOrderValue: 99,
    isOpen: true,
    address: "12 Main St, Sector 4, Bengaluru",
    phone: "+91 9876543210",
    about:
      "Your friendly neighborhood grocery store providing fresh fruits, organic vegetables, and daily essentials since 2012.",
    latitude: 12.97,
    longitude: 77.645,
  },
  {
    id: "store_2",
    name: "Wellness Pharmacy",
    category: "pharmacy",
    logoUrl:
      "https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=100&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=800&q=80",
    rating: 4.8,
    reviewCount: 312,
    distance: 0.8,
    deliveryEta: 15,
    deliveryFee: 10,
    minOrderValue: 50,
    isOpen: true,
    address: "45 Hospital Road, Bengaluru",
    phone: "+91 9876543211",
    about:
      "Certified prescription medication, over-the-counter wellness supplies, and premium baby products with certified pharmacists on duty.",
    latitude: 12.973,
    longitude: 77.635,
  },
  {
    id: "store_3",
    name: "The Bistro Corner",
    category: "food",
    logoUrl:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=100&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    rating: 4.4,
    reviewCount: 84,
    distance: 2.5,
    deliveryEta: 35,
    deliveryFee: 25,
    minOrderValue: 150,
    isOpen: true,
    address: "88 Food Street, Sector 2, Bengaluru",
    phone: "+91 9876543212",
    about:
      "Modern local delicacies, hand-crafted wood-fired pizzas, gourmet pastas, and custom-brewed beverages in a cozy setting.",
    latitude: 12.962,
    longitude: 77.65,
  },
  {
    id: "store_4",
    name: "Urban Threads",
    category: "fashion",
    logoUrl:
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=100&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    rating: 4.2,
    reviewCount: 54,
    distance: 3.1,
    deliveryEta: 45,
    deliveryFee: 30,
    minOrderValue: 200,
    isOpen: true,
    address: "Suite 203, Orion Mall, Bengaluru",
    phone: "+91 9876543213",
    about:
      "Premium clothing collections for men and women, designer accessories, and custom tailors available on site.",
    latitude: 12.985,
    longitude: 77.642,
  },
  {
    id: "store_5",
    name: "Byte Size Electronics",
    category: "electronics",
    logoUrl:
      "https://images.unsplash.com/photo-1588508065123-287b28e013da?w=100&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1588508065123-287b28e013da?w=800&q=80",
    rating: 4.5,
    reviewCount: 92,
    distance: 1.7,
    deliveryEta: 25,
    deliveryFee: 20,
    minOrderValue: 500,
    isOpen: true,
    address: "29 Silicon Complex, Bengaluru",
    phone: "+91 9876543214",
    about:
      "Authorized seller of smartphones, custom laptops, charging peripherals, and audio accessories from top global manufacturers.",
    latitude: 12.978,
    longitude: 77.625,
  },
  {
    id: "store_6",
    name: "Apex General Store",
    category: "general_store",
    logoUrl:
      "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=100&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&q=80",
    rating: 4.3,
    reviewCount: 64,
    distance: 2.2,
    deliveryEta: 22,
    deliveryFee: 15,
    minOrderValue: 100,
    isOpen: true,
    address: "56 Double Road, Indiranagar, Bengaluru",
    phone: "+91 9876543215",
    about:
      "Your daily needs and general store items under one roof, convenient and fast delivery.",
    latitude: 12.968,
    longitude: 77.632,
  },
  {
    id: "store_7",
    name: "Faraway General Store",
    category: "general_store",
    logoUrl:
      "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=100&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80",
    rating: 4.1,
    reviewCount: 38,
    distance: 6.5,
    deliveryEta: 40,
    deliveryFee: 35,
    minOrderValue: 150,
    isOpen: true,
    address: "404 Outer Ring Road, HSR Layout, Bengaluru",
    phone: "+91 9876543216",
    about:
      "A large wholesale general store in HSR Layout offering bulk discounts.",
    latitude: 12.92,
    longitude: 77.61,
  },
];
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod_1",
    storeId: "store_1",
    storeName: "Greenfield Groceries",
    name: "Organic Avocados (Pack of 2)",
    description:
      "Fresh, premium organic Haas avocados imported from local organic farms. Perfectly creamy and ready to eat.",
    imageUrl:
      "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80",
    price: 180,
    discountPrice: 149,
    gstPercent: 5,
    expiryDate: "2026-06-10",
    validityDate: "7 Days Shelf Life",
    refundPolicy: "No questions asked returns on delivery if found spoiled.",
    inStock: true,
    stockCount: 15,
    category: "Fruits & Vegetables",
    isBargainable: true,
    rating: 4.7,
    reviews: [
      {
        id: "rev_1",
        userName: "Anjali Sharma",
        rating: 5,
        comment: "Incredibly fresh and large avocados!",
        createdAt: "2026-06-01",
      },
      {
        id: "rev_2",
        userName: "Rajesh K",
        rating: 4,
        comment: "Good quality but slightly expensive.",
        createdAt: "2026-05-30",
      },
    ],
  },
  {
    id: "prod_2",
    storeId: "store_1",
    storeName: "Greenfield Groceries",
    name: "A2 Cow Milk 1L",
    description:
      "100% pure organic A2 pasteurized cow milk, high in protein and untouched by human hands during packaging.",
    imageUrl:
      "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&q=80",
    price: 90,
    gstPercent: 0,
    expiryDate: "2026-06-04",
    validityDate: "2 Days Shelf Life",
    refundPolicy: "Full refund if curdled on delivery.",
    inStock: true,
    stockCount: 40,
    category: "Dairy & Bread",
    isBargainable: false,
    rating: 4.9,
  },
  {
    id: "prod_3",
    storeId: "store_2",
    storeName: "Wellness Pharmacy",
    name: "Multi-Vitamin Capsules (60 tabs)",
    description:
      "Essential daily vitamins containing vitamins A, C, D, E, B-complex, zinc, and minerals for daily energy booster.",
    imageUrl:
      "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    price: 350,
    discountPrice: 299,
    gstPercent: 12,
    validityDate: "Expiry: Dec 2027",
    refundPolicy: "Returns only on sealed packages within 15 days.",
    inStock: true,
    stockCount: 50,
    category: "Wellness & Health",
    isBargainable: true,
    rating: 4.5,
  },
  {
    id: "prod_4",
    storeId: "store_3",
    storeName: "The Bistro Corner",
    name: "Truffle Mushroom Pizza",
    description:
      "Hand-tossed sourdough pizza topped with wild cremini mushrooms, white truffle oil, fresh mozzarella, and fresh basil.",
    imageUrl:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",
    price: 499,
    discountPrice: 449,
    gstPercent: 18,
    validityDate: "Consume fresh within 2 hours",
    refundPolicy: "Food items cannot be returned.",
    inStock: true,
    stockCount: 20,
    category: "Pizzas",
    isBargainable: true,
    rating: 4.8,
  },
  {
    id: "prod_5",
    storeId: "store_4",
    storeName: "Urban Threads",
    name: "Linen Summer Shirt - Sage Green",
    description:
      "Ultra-breathable 100% premium linen shirt, comfort fit with classic collar. Pre-washed for maximum softness.",
    imageUrl:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80",
    price: 1899,
    discountPrice: 1499,
    gstPercent: 12,
    refundPolicy: "7 days hassle free replacement and sizing exchanges.",
    inStock: true,
    stockCount: 8,
    category: "Men Apparel",
    isBargainable: true,
    rating: 4.3,
  },
  {
    id: "prod_6",
    storeId: "store_5",
    storeName: "Byte Size Electronics",
    name: "Noise Cancelling Earbuds",
    description:
      "Active noise cancelling true wireless earbuds with 30-hour battery life, IPX5 water resistance, and deep bass.",
    imageUrl:
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&q=80",
    price: 2499,
    discountPrice: 1999,
    gstPercent: 18,
    validityDate: "1 Year Brand Warranty",
    refundPolicy: "Replacement within 7 days in case of manufacturing defects.",
    inStock: true,
    stockCount: 12,
    category: "Audio Products",
    isBargainable: true,
    rating: 4.6,
  },
];
