import { Dimensions, StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';

const SCREEN_WIDTH = Dimensions.get('window').width;

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scroll: {
    paddingBottom: 100,
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 16,
    paddingBottom: 20,
    position: 'relative',
    overflow: 'hidden',
  },
  headerBlobLeft: {
    position: 'absolute',
    top: -50,
    left: -30,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  headerBlobRight: {
    position: 'absolute',
    bottom: -60,
    right: -30,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
    marginTop: 8,
  },
  headerStoreInfo: {
    flex: 1,
    marginRight: 12,
  },
  headerGreeting: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.65)',
    fontWeight: '500',
    marginBottom: 2,
  },
  headerStoreName: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.white,
    marginBottom: 6,
  },
  openBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  openDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4ADE80',
  },
  openBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.white,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notifBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.error,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: Colors.primary,
  },
  notifBadgeText: {
    fontSize: 8,
    fontWeight: '700',
    color: Colors.white,
  },
  // ── Alert Strip ───────────────────────────────────────────────────────────
  alertStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(0,0,0,0.18)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 14,
  },
  alertDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: Colors.white,
    flexShrink: 0,
  },
  alertText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.white,
  },
  alertDivider: {
    width: 1,
    height: 14,
    backgroundColor: 'rgba(255,255,255,0.25)',
    marginHorizontal: 2,
  },
  alertDotAmber: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#FCD34D',
    flexShrink: 0,
  },
  alertTextAmber: {
    fontSize: 11,
    fontWeight: '600',
    color: '#FCD34D',
  },

  // ── KPI Row (inside header) ───────────────────────────────────────────────
  kpiRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.15)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 6,
  },
  kpiItem: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  kpiLabel: {
    fontSize: 9,
    color: 'rgba(255,255,255,0.6)',
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 3,
  },
  kpiValue: {
    fontSize: 17,
    fontWeight: '700',
    color: Colors.white,
  },
  kpiSub: {
    fontSize: 9,
    color: 'rgba(255,255,255,0.65)',
    marginTop: 2,
    textAlign: 'center',
  },
  kpiSubGreen: {
    fontSize: 9,
    color: '#4ADE80',
    marginTop: 2,
    fontWeight: '600',
  },
  kpiDivider: {
    width: 1,
    height: 32,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  kpiRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },

  // ── Quick Actions ─────────────────────────────────────────────────────────
  quickActionsCard: {
    backgroundColor: Colors.surface,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 8,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  quickActionItem: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  quickActionIconBg: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 14,
  },

  // ── Section Header ────────────────────────────────────────────────────────
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 22,
    marginBottom: 12,
  },
  sectionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  sectionBadge: {
    fontSize: 9,
    fontWeight: '700',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 20,
  },
  sectionBadgeRed: {
    backgroundColor: Colors.errorBg,
    color: '#991B1B',
  },
  sectionBadgeAmber: {
    backgroundColor: Colors.warningBg,
    color: '#92400E',
  },
  viewAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  viewAllText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.primary,
  },

  // ── Order Card ────────────────────────────────────────────────────────────
  orderCard: {
    backgroundColor: Colors.surface,
    marginHorizontal: 16,
    marginBottom: 10,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    borderLeftWidth: 3,
    borderLeftColor: Colors.primary,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
  },
  orderCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  orderAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  orderAvatarText: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.primary,
  },
  orderMid: {
    flex: 1,
  },
  orderName: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textPrimary,
    marginBottom: 3,
  },
  orderMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  orderPayBadge: {
    fontSize: 9,
    fontWeight: '600',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  orderPayOnline: {
    backgroundColor: Colors.successBg,
    color: '#166534',
  },
  orderPayCod: {
    backgroundColor: Colors.warningBg,
    color: '#92400E',
  },
  orderTime: {
    fontSize: 10,
    color: Colors.textMuted,
  },
  orderRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  orderAmount: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  orderNewBadge: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
  },
  orderNewBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: Colors.white,
  },
  orderDivider: {
    height: 1,
    backgroundColor: Colors.borderLight,
    marginBottom: 10,
  },
  orderMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 12,
  },
  orderMetaText: {
    fontSize: 11,
    color: Colors.textMuted,
  },
  orderMetaDot: {
    fontSize: 11,
    color: Colors.textMuted,
  },
  orderBtnRow: {
    flexDirection: 'row',
    gap: 8,
  },
  orderAcceptBtn: {
    flex: 1,
    height: 36,
    backgroundColor: Colors.primary,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderAcceptText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.white,
  },
  orderRejectBtn: {
    flex: 1,
    height: 36,
    backgroundColor: Colors.surfaceElevated,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  orderRejectText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.textSecondary,
  },

  // ── Bargain Card ──────────────────────────────────────────────────────────
  bargainCard: {
    backgroundColor: Colors.surface,
    marginHorizontal: 16,
    marginBottom: 10,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  bargainCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  bargainAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  bargainAvatarText: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.primary,
  },
  bargainName: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  bargainSub: {
    fontSize: 10,
    color: Colors.textMuted,
    marginTop: 1,
  },
  bargainStatusWaiting: {
    fontSize: 9,
    fontWeight: '700',
    backgroundColor: Colors.warningBg,
    color: '#92400E',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  bargainStatusUrgent: {
    fontSize: 9,
    fontWeight: '700',
    backgroundColor: Colors.errorBg,
    color: '#991B1B',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  bargainStatusCountered: {
    fontSize: 9,
    fontWeight: '700',
    backgroundColor: Colors.infoBg,
    color: '#1E40AF',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  bargainPricePanel: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.background,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 10,
  },
  bargainPriceSide: {
    flex: 1,
  },
  bargainPriceLabel: {
    fontSize: 9,
    color: Colors.textMuted,
    marginBottom: 2,
  },
  bargainPriceCustomer: {
    fontSize: 17,
    fontWeight: '700',
    color: Colors.error,
  },
  bargainPriceMerchant: {
    fontSize: 17,
    fontWeight: '700',
    color: Colors.success,
  },
  bargainPriceCounter: {
    fontSize: 17,
    fontWeight: '700',
    color: Colors.info,
  },
  bargainPriceVsSep: {
    width: 1,
    height: 28,
    backgroundColor: Colors.border,
    marginHorizontal: 12,
  },
  bargainVsText: {
    fontSize: 11,
    color: Colors.textMuted,
    position: 'absolute',
    left: '47%',
  },
  bargainExpiry: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 12,
  },
  bargainExpiryDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  bargainExpiryText: {
    fontSize: 10,
    fontWeight: '500',
  },
  bargainGapText: {
    fontSize: 10,
    color: Colors.textMuted,
    marginLeft: 'auto',
  },
  bargainBtnRow: {
    flexDirection: 'row',
    gap: 7,
  },
  bargainAcceptBtn: {
    flex: 1,
    height: 34,
    backgroundColor: Colors.success,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bargainAcceptText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.white,
  },
  bargainCounterBtn: {
    flex: 1,
    height: 34,
    backgroundColor: Colors.primaryLight,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bargainCounterText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.primary,
  },
  bargainDeclineBtn: {
    flex: 1,
    height: 34,
    backgroundColor: Colors.surfaceElevated,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  bargainDeclineText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.textSecondary,
  },

  // ── Inventory Alert Row ───────────────────────────────────────────────────
  inventoryCard: {
    backgroundColor: Colors.surface,
    marginHorizontal: 16,
    borderRadius: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 10,
  },
  inventoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
  },
  inventoryRowBorder: {
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
  },
  inventoryImgBox: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: Colors.surfaceElevated,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  inventoryEmoji: {
    fontSize: 22,
  },
  inventoryInfo: {
    flex: 1,
  },
  inventoryName: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textPrimary,
    marginBottom: 2,
  },
  inventoryQtyRed: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.error,
  },
  inventoryQtyAmber: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.warning,
  },
  inventoryProgBg: {
    height: 4,
    backgroundColor: Colors.surfaceElevated,
    borderRadius: 2,
    marginTop: 5,
    overflow: 'hidden',
  },
  inventoryProg: {
    height: 4,
    borderRadius: 2,
  },
  inventoryActionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    flexShrink: 0,
  },
  inventoryActionText: {
    fontSize: 11,
    fontWeight: '600',
  },

  // ── Revenue Snapshot ──────────────────────────────────────────────────────
  revenueGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    gap: 10,
  },
  revenueSnapCard: {
    width: (SCREEN_WIDTH - 42) / 2,
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: 6,
  
  },
  revenueCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  revenueIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  revenuePeriodPill: {
    backgroundColor: Colors.surfaceElevated,
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  revenuePeriodText: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.textMuted,
  },
  revenueSnapLabel: {
    fontSize: 11,
    color: Colors.textMuted,
    fontWeight: '500',
  },
  revenueSnapValue: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.textPrimary,
  },

  // ── Activity Timeline ─────────────────────────────────────────────────────
  timelineWrap: {
    backgroundColor: Colors.surface,
    marginHorizontal: 16,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 8,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineLeft: {
    alignItems: 'center',
    width: 28,
  },
  timelineIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  timelineConnector: {
    width: 1.5,
    flex: 1,
    marginVertical: 3,
  },
  timelineRight: {
    flex: 1,
    paddingBottom: 16,
  },
  timelineLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  timelineTime: {
    fontSize: 10,
    color: Colors.textMuted,
    marginTop: 2,
  },

  // ── Skeleton ──────────────────────────────────────────────────────────────
  skeletonHeader: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 16,
    paddingBottom: 20,
    gap: 12,
  },
  skeletonBlock: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 8,
  },
  skeletonCard: {
    backgroundColor: Colors.surface,
    marginHorizontal: 16,
    marginBottom: 10,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: 10,
  },
  skeletonLine: {
    backgroundColor: Colors.borderLight,
    borderRadius: 6,
  },
  skeletonCircle: {
    backgroundColor: Colors.borderLight,
    borderRadius: 999,
  },

  // ── Gauge (kept for compatibility) ────────────────────────────────────────
  gaugeWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  gaugeInner: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gaugeScore: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  gaugePercent: {
    fontSize: 8,
    color: Colors.textMuted,
    fontWeight: '600',
    marginTop: -2,
  },
});
