import { StyleSheet } from 'react-native';

export const floatingCartStyles = StyleSheet.create({
  floatingCart: {
    position: 'absolute',
    bottom: 96,
    left: 48,
    right: 48,
    height: 64,
    borderRadius: 32,
    borderWidth: 0.5,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    elevation: 6,
    shadowColor: 'rgba(0, 77, 87, 0.25)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  cartMainArea: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cartImageWrapper: {
    width: 52,
    height: 52,
    borderRadius: 26,
    overflow: 'hidden',
    marginRight: 12,
  },
  cartImage: {
    width: '100%',
    height: '100%',
  },
  cartLeft: {
    flex: 1,
    justifyContent: 'center',
  },
  viewCartText: {
    fontSize: 15,
  },
  cartQtyText: {
    fontSize: 13,
    marginTop: 2,
  },
  cartChevronCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#047857',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  viewCartFloatingPillWrapper: {
    position: 'absolute',
    top: -20,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  viewCartFloatingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 0.5,
    elevation: 4,
    shadowColor: 'rgba(0, 77, 87, 0.25)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
  },
  viewCartFloatingPillIcon: {
    marginRight: 6,
  },
  viewCartFloatingPillText: {
    color: '#16A34A',
    fontSize: 13,
  },
  viewCartFloatingPillBadgeWrapper: {
    position: 'absolute',
    top: -14,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  viewCartFloatingPillBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 0.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
