import { GlobalCategory, Shop, ShopCategory, ShopProduct } from '../../../types/shared';

export const MOCK_GLOBAL_CATEGORIES: GlobalCategory[] = [
  {
    id: 'cat_groceries',
    name: 'Vegetables & Fruits',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&q=80',
    subcategories: [
      { id: 'subcat_leafy', name: 'Leafy Vegetables', image: '' },
      { id: 'subcat_fruits', name: 'Fresh Fruits', image: '' },
    ],
  },
  {
    id: 'cat_dairy',
    name: 'Dairy & Eggs',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&q=80',
    subcategories: [{ id: 'subcat_milk', name: 'Milk & Curd', image: '' }],
  },
  {
    id: 'cat_pharmacy',
    name: 'Pharmacy & Wellness',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=200&q=80',
    subcategories: [
      { id: 'subcat_otc', name: 'OTC Medicines', image: '' },
      { id: 'subcat_supplements', name: 'Supplements', image: '' },
    ],
  },
  {
    id: 'cat_food',
    name: 'Food & Beverages',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=200&q=80',
    subcategories: [
      { id: 'subcat_pizza', name: 'Pizzas', image: '' },
      { id: 'subcat_snacks', name: 'Snacks', image: '' },
    ],
  },
  {
    id: 'cat_fashion',
    name: 'Fashion',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=200&q=80',
    subcategories: [
      { id: 'subcat_men', name: "Men's Apparel", image: '' },
      { id: 'subcat_women', name: "Women's Apparel", image: '' },
    ],
  },
  {
    id: 'cat_electronics',
    name: 'Electronics',
    image: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=200&q=80',
    subcategories: [
      { id: 'subcat_audio', name: 'Audio', image: '' },
      { id: 'subcat_mobile', name: 'Mobiles & Accessories', image: '' },
    ],
  },
  {
    id: 'cat_general',
    name: 'General Store',
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=200&q=80',
    subcategories: [{ id: 'subcat_household', name: 'Household', image: '' }],
  },
];

interface MockShop extends Shop {
  shopCategoryIds?: string[];
  shopSubcategoryIds?: string[];
}

export const MOCK_SHOPS: MockShop[] = [
  {
    id: 'store_1',
    name: 'Greenfield Groceries',
    description: 'Your friendly neighborhood grocery store providing fresh fruits, organic vegetables, and daily essentials.',
    phone_number: '+919876543210',
    is_open: true,
    is_verified: true,
    average_rating: '4.60',
    min_order: '99.00',
    delivery_radius_km: '5.00',
    surge_fee: '0.00',
    cod_toggle: true,
    shop_types: [{ id: 'st_grocery', name: 'Grocery', slug: 'grocery' }],
    shopCategoryIds: ['cat_groceries', 'cat_dairy'],
    shopSubcategoryIds: ['subcat_leafy', 'subcat_fruits', 'subcat_milk'],
  },
  {
    id: 'store_2',
    name: 'Wellness Pharmacy',
    description: 'Certified prescription medication, OTC wellness supplies, and premium baby products.',
    phone_number: '+919876543211',
    is_open: true,
    is_verified: true,
    average_rating: '4.80',
    min_order: '50.00',
    delivery_radius_km: '6.00',
    surge_fee: '0.00',
    cod_toggle: true,
    shop_types: [{ id: 'st_pharmacy', name: 'Pharmacy', slug: 'pharmacy' }],
    shopCategoryIds: ['cat_pharmacy'],
    shopSubcategoryIds: ['subcat_otc', 'subcat_supplements'],
  },
  {
    id: 'store_3',
    name: 'The Bistro Corner',
    description: 'Modern local delicacies, hand-crafted wood-fired pizzas, gourmet pastas, and custom-brewed beverages.',
    phone_number: '+919876543212',
    is_open: true,
    is_verified: true,
    average_rating: '4.40',
    min_order: '150.00',
    delivery_radius_km: '4.00',
    surge_fee: '5.00',
    cod_toggle: false,
    shop_types: [{ id: 'st_restaurant', name: 'Restaurant', slug: 'restaurant' }],
    shopCategoryIds: ['cat_food'],
    shopSubcategoryIds: [
      'subcat_pizza',
      'subcat_biryani',
      'subcat_fried_rice',
      'subcat_chicken_curry',
      'subcat_shawarma',
      'subcat_dosa',
      'subcat_khichdi',
      'subcat_idli',
      'subcat_curd_rice',
      'subcat_burger',
      'subcat_ice_cream',
      'subcat_desserts'
    ],
  },
  {
    id: 'store_4',
    name: 'Urban Threads',
    description: 'Premium clothing collections for men and women, designer accessories, and custom tailors.',
    phone_number: '+919876543213',
    is_open: true,
    is_verified: true,
    average_rating: '4.20',
    min_order: '200.00',
    delivery_radius_km: '8.00',
    surge_fee: '0.00',
    cod_toggle: true,
    shop_types: [{ id: 'st_fashion', name: 'Fashion', slug: 'fashion' }],
    shopCategoryIds: ['cat_fashion'],
    shopSubcategoryIds: ['subcat_men'],
  },
  {
    id: 'store_5',
    name: 'Byte Size Electronics',
    description: 'Authorized seller of smartphones, custom laptops, charging peripherals, and audio accessories.',
    phone_number: '+919876543214',
    is_open: true,
    is_verified: true,
    average_rating: '4.50',
    min_order: '500.00',
    delivery_radius_km: '10.00',
    surge_fee: '0.00',
    cod_toggle: false,
    shop_types: [{ id: 'st_electronics', name: 'Electronics', slug: 'electronics' }],
    shopCategoryIds: ['cat_electronics'],
    shopSubcategoryIds: ['subcat_audio'],
  },
  {
    id: 'store_6',
    name: 'Apex General Store',
    description: 'Your daily needs and general store items under one roof, convenient and fast delivery.',
    phone_number: '+919876543215',
    is_open: true,
    is_verified: true,
    average_rating: '4.30',
    min_order: '100.00',
    delivery_radius_km: '5.00',
    surge_fee: '0.00',
    cod_toggle: true,
    shop_types: [{ id: 'st_general', name: 'General Store', slug: 'general-store' }],
    shopCategoryIds: ['cat_general'],
    shopSubcategoryIds: ['subcat_household'],
  },
  {
    id: 'store_7',
    name: 'Faraway General Store',
    description: 'A large wholesale general store in HSR Layout offering bulk discounts.',
    phone_number: '+919876543216',
    is_open: true,
    is_verified: true,
    average_rating: '4.10',
    min_order: '150.00',
    delivery_radius_km: '12.00',
    surge_fee: '10.00',
    cod_toggle: true,
    shop_types: [{ id: 'st_general', name: 'General Store', slug: 'general-store' }],
    shopCategoryIds: ['cat_general'],
    shopSubcategoryIds: ['subcat_household'],
  },
];

export const MOCK_SHOP_CATEGORIES: Record<string, ShopCategory[]> = {
  store_1: [
    {
      id: 'cat_groceries',
      name: 'Vegetables & Fruits',
      image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&q=80',
      product_count: 1,
      subcategories: [{ id: 'subcat_fruits', name: 'Fresh Fruits', image: '', product_count: 1 }],
    },
    {
      id: 'cat_dairy',
      name: 'Dairy & Eggs',
      image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&q=80',
      product_count: 1,
      subcategories: [{ id: 'subcat_milk', name: 'Milk & Curd', image: '', product_count: 1 }],
    },
  ],
  store_2: [
    {
      id: 'cat_pharmacy',
      name: 'Pharmacy & Wellness',
      image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=200&q=80',
      product_count: 1,
      subcategories: [{ id: 'subcat_supplements', name: 'Supplements', image: '', product_count: 1 }],
    },
  ],
  store_3: [
    {
      id: 'cat_food',
      name: 'Food & Beverages',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=200&q=80',
      product_count: 1,
      subcategories: [{ id: 'subcat_pizza', name: 'Pizzas', image: '', product_count: 1 }],
    },
  ],
  store_4: [
    {
      id: 'cat_fashion',
      name: 'Fashion',
      image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=200&q=80',
      product_count: 1,
      subcategories: [{ id: 'subcat_men', name: "Men's Apparel", image: '', product_count: 1 }],
    },
  ],
  store_5: [
    {
      id: 'cat_electronics',
      name: 'Electronics',
      image: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=200&q=80',
      product_count: 1,
      subcategories: [{ id: 'subcat_audio', name: 'Audio', image: '', product_count: 1 }],
    },
  ],
};

export const MOCK_SHOP_PRODUCTS: Record<string, ShopProduct[]> = {
  store_1: [
    {
      id: 'prod_1',
      name: 'Organic Avocados (Pack of 2)',
      description:
        'Fresh, premium organic Haas avocados imported from local organic farms. Perfectly creamy and ready to eat.',
      image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80',
      is_perishable: true,
      category: { id: 'cat_groceries', name: 'Vegetables & Fruits', image: '' },
      subcategory: { id: 'subcat_fruits', name: 'Fresh Fruits', image: '' },
      brand: null,
      variants: [
        {
          id: 'prod_1_v1',
          name: 'Pack of 2',
          unit: { id: 'unit_pack', name: 'Pack', symbol: 'pack', unit_type: 'COUNT' },
          quantity_per_unit: '2.0000',
          sku: 'VEG-AVO-2PK',
          mrp: '180.00',
          selling_price: '149.00',
          image: '',
          position: 0,
          available_stock: '15.0000',
          is_in_stock: true,
        },
      ],
    },
    {
      id: 'prod_2',
      name: 'A2 Cow Milk 1L',
      description:
        '100% pure organic A2 pasteurized cow milk, high in protein and untouched by human hands during packaging.',
      image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&q=80',
      is_perishable: true,
      category: { id: 'cat_dairy', name: 'Dairy & Eggs', image: '' },
      subcategory: { id: 'subcat_milk', name: 'Milk & Curd', image: '' },
      brand: null,
      variants: [
        {
          id: 'prod_2_v1',
          name: '1 Litre',
          unit: { id: 'unit_litre', name: 'Litre', symbol: 'L', unit_type: 'VOLUME' },
          quantity_per_unit: '1.0000',
          sku: 'DAI-MILK-1L',
          mrp: '90.00',
          selling_price: '90.00',
          image: '',
          position: 0,
          available_stock: '40.0000',
          is_in_stock: true,
        },
      ],
    },
  ],
  store_2: [
    {
      id: 'prod_3',
      name: 'Multi-Vitamin Capsules (60 tabs)',
      description:
        'Essential daily vitamins containing vitamins A, C, D, E, B-complex, zinc, and minerals for daily energy booster.',
      image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80',
      is_perishable: false,
      category: { id: 'cat_pharmacy', name: 'Pharmacy & Wellness', image: '' },
      subcategory: { id: 'subcat_supplements', name: 'Supplements', image: '' },
      brand: null,
      variants: [
        {
          id: 'prod_3_v1',
          name: '60 Tablets',
          unit: { id: 'unit_piece', name: 'Piece', symbol: 'pcs', unit_type: 'COUNT' },
          quantity_per_unit: '60.0000',
          sku: 'PHA-MVIT-60',
          mrp: '350.00',
          selling_price: '299.00',
          image: '',
          position: 0,
          available_stock: '50.0000',
          is_in_stock: true,
        },
      ],
    },
  ],
  store_3: [
    {
      id: 'prod_4',
      name: 'Truffle Mushroom Pizza',
      description:
        'Hand-tossed sourdough pizza topped with wild cremini mushrooms, white truffle oil, fresh mozzarella, and fresh basil.',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80',
      is_perishable: true,
      category: { id: 'cat_food', name: 'Food & Beverages', image: '' },
      subcategory: { id: 'subcat_pizza', name: 'Pizzas', image: '' },
      brand: null,
      variants: [
        {
          id: 'prod_4_v1',
          name: 'Regular',
          unit: { id: 'unit_piece', name: 'Piece', symbol: 'pcs', unit_type: 'COUNT' },
          quantity_per_unit: '1.0000',
          sku: 'FOOD-PIZZA-TRF',
          mrp: '499.00',
          selling_price: '449.00',
          image: '',
          position: 0,
          available_stock: '20.0000',
          is_in_stock: true,
        },
      ],
    },
  ],
  store_4: [
    {
      id: 'prod_5',
      name: 'Linen Summer Shirt - Sage Green',
      description:
        'Ultra-breathable 100% premium linen shirt, comfort fit with classic collar. Pre-washed for maximum softness.',
      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80',
      is_perishable: false,
      category: { id: 'cat_fashion', name: 'Fashion', image: '' },
      subcategory: { id: 'subcat_men', name: "Men's Apparel", image: '' },
      brand: null,
      variants: [
        {
          id: 'prod_5_v1',
          name: 'M',
          unit: { id: 'unit_piece', name: 'Piece', symbol: 'pcs', unit_type: 'COUNT' },
          quantity_per_unit: '1.0000',
          sku: 'FASH-SHIRT-SG-M',
          mrp: '1899.00',
          selling_price: '1499.00',
          image: '',
          position: 0,
          available_stock: '8.0000',
          is_in_stock: true,
        },
      ],
    },
  ],
  store_5: [
    {
      id: 'prod_6',
      name: 'Noise Cancelling Earbuds',
      description:
        'Active noise cancelling true wireless earbuds with 30-hour battery life, IPX5 water resistance, and deep bass.',
      image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&q=80',
      is_perishable: false,
      category: { id: 'cat_electronics', name: 'Electronics', image: '' },
      subcategory: { id: 'subcat_audio', name: 'Audio', image: '' },
      brand: null,
      variants: [
        {
          id: 'prod_6_v1',
          name: 'Standard',
          unit: { id: 'unit_piece', name: 'Piece', symbol: 'pcs', unit_type: 'COUNT' },
          quantity_per_unit: '1.0000',
          sku: 'ELEC-EARBUD-NC',
          mrp: '2499.00',
          selling_price: '1999.00',
          image: '',
          position: 0,
          available_stock: '12.0000',
          is_in_stock: true,
        },
      ],
    },
  ],
};
